overrides:
  lightningcss: 1.30.1

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.3'
  - '@expo/prebuild-config@57.0.3'
  - expo-modules-autolinking@57.0.3
  - expo-modules-core@57.0.1
  - expo@57.0.1

allowBuilds:
  unrs-resolver: set this to true or false
