#!/usr/bin/env node
/**
 * Scrapes the full Open University course catalog and writes
 * src/app/api/catalog.generated.json — a server-only JSON asset imported by the
 * catalog API route (never shipped to the client bundle).
 *
 * Iterates every `validation.ok` sitecode/sitetype/departmentcode combination in
 * openu-codes.json (one HTTP endpoint per department/subject site), fetching all
 * pages per combo. The same course frequently appears under multiple combos
 * (cross-listed across departments); rows are deduped by courseNumber with an
 * explicit merge policy — see mergeEntry().
 *
 * Faculty/subject data (`faculty`) is an ARRAY: a course can legitimately belong
 * to more than one department, so nothing is dropped in favor of a single
 * "primary" value.
 *
 * NOTE ON `type`: "חובה" (required) is degree-specific, not an intrinsic property
 * of a course (required for one degree, elective for another) — the endpoint does
 * not carry it, so it can never be scraped. This script only distinguishes
 * 'סמינר' (via the isSeminar heuristic) from the default 'בחירה'. Whatever marks
 * a course as חובה for a given degree must live in a separate per-degree
 * requirements map, not here.
 *
 * The endpoint is paginated; we increment `page` until it returns an empty array.
 * Combos are fetched sequentially (be a good citizen to the OpenU endpoint).
 *
 * KNOWN GAP: department-page discovery (the combos in openu-codes.json) is not
 * fully exhaustive — at least 2 core mandatory courses (20109 אלגברה לינארית 1,
 * 20417 אלגוריתמים) are not reachable through any of the 31 combos. Accepted and
 * documented rather than fixed; see CATALOG_PLAN.md "Known limitation" section.
 *
 * Run with: npm run scrape:catalog
 */

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CODES_PATH = resolve(__dirname, '../openu-codes.json');
const OUTPUT_PATH = resolve(__dirname, '../src/app/api/catalog.generated.json');
const FACULTIES_PATH = resolve(__dirname, '../src/data/faculties.generated.ts');

/**
 * Derive the distinct faculty list from the scraped entries and write it as a tiny
 * client-bundled constant. Unlike catalog.generated.json (server-only, 273 KB), this
 * is a few KB of short strings read straight from memory by the Profile picker.
 */
async function writeFaculties(entries) {
  const faculties = Array.from(
    new Set(entries.flatMap((entry) => entry.faculty).map((f) => String(f).trim()).filter(Boolean)),
  ).sort((a, b) => a.localeCompare(b, 'he'));

  const header =
    '// AUTO-GENERATED by scripts/scrape-catalog.mjs — do not edit by hand.\n' +
    '// The distinct set of faculties (פקולטה) across the course catalog.\n';
  const body = `export const FACULTIES: readonly string[] = [\n${faculties
    .map((f) => `  ${JSON.stringify(f)},`)
    .join('\n')}\n];\n`;
  await writeFile(FACULTIES_PATH, header + body);
  return faculties.length;
}

const API =
  'https://academic.openu.ac.il/_layouts/15/OpenU_WWW/Handlers/GetCoursesBySiteCodeHandler.ashx';

/** Fixed for every combo; sitecode/sitetype/departmentcode vary per combo. */
const PARAMS = {
  subject: '',
  level: '',
  semesterfrom: '-1',
  semesterto: '-1',
  marchivdaat: '',
  freeText: '',
};

async function loadCombos() {
  const raw = await readFile(CODES_PATH, 'utf8');
  const codes = JSON.parse(raw);
  const combos = codes.candidates
    .filter((candidate) => candidate.validation?.ok)
    .map(({ sitecode, sitetype, departmentcode }) => ({ sitecode, sitetype, departmentcode }));

  // Sort deterministically so re-runs merge in the same order regardless of how
  // openu-codes.json happens to list candidates (keeps output diffs stable).
  combos.sort(
    (a, b) =>
      a.sitecode.localeCompare(b.sitecode) ||
      a.sitetype.localeCompare(b.sitetype) ||
      a.departmentcode.localeCompare(b.departmentcode),
  );
  return combos;
}

function buildUrl(combo, page) {
  const url = new URL(API);
  url.searchParams.set('page', String(page));
  const params = { ...PARAMS, ...combo };
  for (const [key, value] of Object.entries(params)) url.searchParams.set(key, value);
  return url.toString();
}

async function fetchAllCourses(combo) {
  const rows = [];
  for (let page = 0; ; page++) {
    const res = await fetch(buildUrl(combo, page));
    if (!res.ok) throw new Error(`Page ${page} request failed: ${res.status} ${res.statusText}`);
    const batch = await res.json();
    if (!Array.isArray(batch) || batch.length === 0) break;
    rows.push(...batch);
    process.stdout.write(`\r  page ${page} — ${rows.length} rows so far`);
  }
  process.stdout.write('\n');
  return rows;
}

// --- Field mapping ---------------------------------------------------------

/** Strip leading zeros so '04101' matches the existing '4101' style. */
function normalizeCourseNumber(courseIDField) {
  const stripped = String(courseIDField ?? '').replace(/^0+/, '');
  return stripped || '0';
}

/** Remove RTL/LTR control marks and surrounding whitespace from scraped text. */
function cleanName(value) {
  return String(value ?? '')
    .replace(/[‎‏‪-‮]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/** All subjects/departments this course is listed under (deduped, insertion order). */
function mapFaculty(row) {
  const subjects = (row.subjectsField ?? []).map((s) => cleanName(s.teurField)).filter(Boolean);
  return Array.from(new Set(subjects));
}

function mapLevel(levelField) {
  if (!levelField) return undefined;
  if (levelField.includes('תואר שני') || levelField.includes('מתקדם')) return 'מ';
  if (levelField.includes('רגיל')) return 'ר';
  return undefined;
}

function isSeminar(row) {
  if (row.seminarField === 'כ') return true;
  const name = cleanName(row.courseNameField);
  return name.startsWith('סמינר') || name.startsWith('סדנה');
}

function toEntry(row) {
  const credits = row.creditsField != null ? Number(row.creditsField) : NaN;
  return {
    courseNumber: normalizeCourseNumber(row.courseIDField),
    name: cleanName(row.courseNameField),
    faculty: mapFaculty(row),
    credits: Number.isFinite(credits) ? credits : undefined,
    type: isSeminar(row) ? 'סמינר' : 'בחירה',
    level: mapLevel(row.levelField),
  };
}

/**
 * Merge policy on courseNumber collision (a course appearing under multiple
 * combos): prefer non-empty name/credits/level; union faculty arrays in
 * first-encountered order (the earliest-processed combo's subject becomes the
 * array's first/"primary" entry — consumers that need a single faculty use
 * `faculty[0]`); a course is a seminar if *any* occurrence says so.
 */
function mergeEntry(existing, incoming) {
  const faculty = [...existing.faculty];
  for (const f of incoming.faculty) if (!faculty.includes(f)) faculty.push(f);
  return {
    courseNumber: existing.courseNumber,
    name: existing.name || incoming.name,
    faculty,
    credits: existing.credits ?? incoming.credits,
    type: existing.type === 'סמינר' || incoming.type === 'סמינר' ? 'סמינר' : 'בחירה',
    level: existing.level ?? incoming.level,
  };
}

async function main() {
  const combos = await loadCombos();
  console.log(`Scraping ${combos.length} sitecode/sitetype/departmentcode combos...`);

  const merged = new Map();
  for (const [index, combo] of combos.entries()) {
    console.log(
      `[${index + 1}/${combos.length}] sitecode=${combo.sitecode} sitetype=${combo.sitetype} departmentcode=${combo.departmentcode}`,
    );
    const rows = await fetchAllCourses(combo);
    for (const row of rows) {
      const entry = toEntry(row);
      const existing = merged.get(entry.courseNumber);
      merged.set(entry.courseNumber, existing ? mergeEntry(existing, entry) : entry);
    }
  }

  const entries = Array.from(merged.values()).sort(
    (a, b) => Number(a.courseNumber) - Number(b.courseNumber) || a.courseNumber.localeCompare(b.courseNumber),
  );

  await writeFile(OUTPUT_PATH, `${JSON.stringify(entries, null, 2)}\n`);
  console.log(`\nWrote ${entries.length} deduped courses (from ${combos.length} combos) to ${OUTPUT_PATH}`);

  const facultyCount = await writeFaculties(entries);
  console.log(`Wrote ${facultyCount} distinct faculties to ${FACULTIES_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
